// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbapdohbczqyomzmjhij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiYXBkb2hiY3pxeW9tem1qaGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mzk4NTgsImV4cCI6MjA2MDAxNTg1OH0.x8EZk9mM3W2uMK3UAvq0_rw_UASr_AwlHQshgXOvZ3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});